apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraud-detection-service.fullname" . }}
  labels:
    {{- include "fraud-detection-service.labels" . | nindent 4 }}
data:
  .env: |
    {{- .Values.config.env | nindent 4 }}