services:
  localserver:
    url: http://127.0.0.1:8080/
    response_header_timeout_seconds: 5

bundles:
  frauddetection:
    service: localserver
    resource: frauddetection.tar.gz
    # persist: true
    polling:
      min_delay_seconds: 5
      max_delay_seconds: 10
  alerts:
    service: localserver
    resource: alerts.tar.gz
    # persist: true
    polling:
      min_delay_seconds: 5
      max_delay_seconds: 10
