apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "real-time-alerts.fullname" . }}
  labels:
    {{- include "real-time-alerts.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config.opa | nindent 4 }}