apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mvn-build-and-deploy-pipeline
spec:
  workspaces:
    - name: git-source
      description: The git repo
    - name: dockerconfig
      description: Contains config.json for Docker Login
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: master
    - name: pathToContext
      description: The path to the build context, used by Kaniko & Maven - within the workspace
      default: src
    - name: dockerfile
      default: ./Dockerfile
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
    - name: chartsDir
      description: Directory for Helm chart to use for deployment
      default: charts/
    - name: releaseName
      description: Name to use for the Helm release during deployment
      default: my-app
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - clone-repo
      params:
        - name: CONTEXT_DIR
          value: $(params.pathToContext)
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
      workspaces:
        - name: maven-settings
          workspace: git-source
        - name: source
          workspace: git-source
    - name: source-to-image
      taskRef:
        name: kaniko
      runAfter:
        - maven-run
      workspaces:
        - name: source
          workspace: git-source
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
        - name: DOCKERFILE
          value: $(params.dockerfile)
    - name: deploy-to-cluster
      taskRef:
        name: helm-upgrade-from-source
      runAfter:
        - source-to-image
      workspaces:
        - name: source
          workspace: git-source
      params:
        - name: charts_dir
          value: $(params.chartsDir)
        - name: release_name
          value: $(params.releaseName)
        - name: overwrite_values
          value: image.repository=$(params.imageUrl),image.tag=$(params.imageTag)