apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-kafka
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: persistent-claim
      size: 5Gi
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: 512m
      limits:
        memory: 2Gi
        cpu: 512m
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 512m
      limits:
        memory: 2Gi
        cpu: 512m
  # entityOperator:
  #   tlsSidecar:
  #     resources:
  #       requests:
  #         cpu: 200m
  #         memory: 64Mi
  #       limits:
  #         cpu: 200m
  #         memory: 64Mi
  #   topicOperator:
  #     resources:
  #       requests:
  #         memory: 128Mi
  #         cpu: 256m
  #       limits:
  #         memory: 128Mi
  #         cpu: 256m
  #   userOperator:
  #     resources:
  #       requests:
  #         memory: 128Mi
  #         cpu: 256m
  #       limits:
  #         memory: 128Mi
  #         cpu: 256m