apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "marketing-platform-etl.fullname" . }}
  labels:
    {{- include "marketing-platform-etl.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.job.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "marketing-platform-etl.fullname" . }}
          labels:
            {{- include "marketing-platform-etl.labels" . | nindent 12 }}
        {{- with .Values.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          {{- include "marketing-platform-etl.selectorLabels" . | nindent 10 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "marketing-platform-etl.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                - name: KAFKA_BOOTSTRAP_SERVER
                  value: {{ .Values.config.bootstrapServers }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
